### ISSUE TITLE
Spray life time

### ISSUE THREAD

**Issue by z1ntex** [NockyCZ/eSprays#3]
Is it possible to make the spray disappear over time like VALVE does?

**Comment by NockyCZ** [comment]
Im afraid not, i did not find any function to set the decal lifetime

**Comment by z1ntex** [comment]
@NockyCZ 
Maybe this will help you. It worked here.
[Архив WinRAR.zip](https://github.com/NockyCZ/eSprays/files/7637064/WinRAR.zip)
